id = "koda-theme"
name = "Koda Theme"
version = "0.0.1"
schema_version = 1
authors = ["Markos Narinian <manarinian@gmail.com>", "Karl Oskar Joosep Nurm"]
description = "Koda theme ported from oskarnurm/koda.nvim by Karl Oskar Joosep Nurm"
repository = "https://github.com/markosnarinian/koda-zed"
